# deploy_kubernetes.yml

---
- name: Deploy Docker image to Kubernetes
  hosts: localhost
  become: true
  connection: local   
  tasks:
    - name: Deploy Kubernetes Deployment
      k8s:
        api_version: apps/v1
        kind: Deployment
        name: abc-deployment
        namespace: default
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-deployment
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: abc-app
            template:
              metadata:
                labels:
                  app: abc-app
              spec:
                containers:
                - name: abc-container
                  image: shrutir20/abc_prj_gcp:latest
                  ports:
                  - containerPort: 80
