- hosts: localhost
  become: yes
  connection: local
  tasks:
        # - name: login to docker hub
        #   command: docker login -u shrutir20 -p Docker@2023May09
        - name: build docker image
          command: docker build -t shrutir20/abctechmavenprj .
        - name: push image to docker hub
          command: docker push shrutir20/abctechmavenprj
        # - name: Build an image and push it to a private repo
        #   community.docker.docker_image:
        #       build:
        #           path: "/home/edureka/Desktop"
        #       name: docker.io/shrutir20/abctechmavenprj
        #       #tag: test
        #       push: true
        #       source: build
        #   register: out
        # - debug:
        #       var: out  
        - name: start a container
          community.docker.docker_container:
             name: abc-application
             image: shrutir20/abctechmavenprj
             state: started
             ports:
                 - 1234:8080
             #restart: true
          register: out
        - debug:
              var: out
             #- name: Deploying to kubernetes
        - name: Create a Deployment by reading the definition from a local file 
          command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/deployment.yml"    
          register: out
        - debug:
              var: out
