apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: abctech-k8s-deployment
spec:
  selector:
    matchLabels:
      app: abc-tech-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: abc-tech-app
    spec:
      containers:
        - name: abc-tech-app
          image: shrutir20/abcprj:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: abc-tech-service
spec:
  selector:
    app: abc-tech-app
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
